# Generated by Django 4.0.5 on 2022-07-03 18:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название ингридиента', max_length=50, verbose_name='Название')),
                ('amount', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Ингридиентов должны быть не менее 1!')], verbose_name='Количество')),
                ('unit', models.CharField(choices=[('mg', 'мг'), ('ml', 'мл'), ('unitless', 'шт')], default='unitless', max_length=10, verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Наименаование тэга', max_length=50, verbose_name='Тэг')),
                ('hex_code', models.CharField(max_length=12, verbose_name='HEX код')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название блюда', max_length=50, verbose_name='Название')),
                ('description', models.TextField(default='Текстовое описание', verbose_name='Описание')),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время приготовления - положительное!')], verbose_name='Минут на приготовление')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('ingridients', models.ManyToManyField(related_name='recipes', to='recipes.ingridient')),
                ('tag', models.ManyToManyField(related_name='recipes', to='recipes.tag')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('title', 'author'),
            },
        ),
    ]
