# Generated by Django 3.2.14 on 2022-07-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amountofingredient',
            unique_together=set(),
        ),
    ]
