# Generated by Django 3.2.14 on 2022-07-30 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_amountofingredient_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amountofingredient',
            unique_together={('ingredient', 'recipe')},
        ),
    ]
